dist:     xenial    
sudo:     required  

language: cpp

os:
    - linux

compiler:
    - g++

env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

# install:
#     - source install-linux.bash

script:
    - cd build
    - travis_wait 1000000 ./run

